const char *getHelp();
const char* getVersion();
int listDir(void (*itemFunc)());
void getItems(DIR* dir);
bool isDir(const char* path);
void getByColumn(DIR* dir);
void getHidden(DIR* dir);
void getRecursively(/*DIR* dir*/);
void sortItems();
void parseArgs(int argc, char** argv);