name: CI for Genutils

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  build-lin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build for Linux
        run: make
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build for Windows
        run: make